  - name: 'Instalando programas... pode demorar um pouco'
    apt:
      update_cache: yes
      name:
        - php7.2
        - apache2
        - libapache2-mod-php7.2
        - php7.2-gd
        - libmcrypt-dev
        - php7.2-mysql
      state: latest
    become: yes
